module = "github.com/miekg/dns"

description = """
An attacker can craft a malicious DNS zone file which will cause
[`ParseZone`] to panic due to a nil pointer dereference.
"""

cve = "CVE-2018-17419"

credit = "@tr3ee"

symbols = ["setTA"]

[[versions]]
fixed = "v1.0.10"

[links]
commit = "https://github.com/miekg/dns/commit/501e858f679edecd4a38a86317ce50271014a80d"
context = ["https://github.com/miekg/dns/issues/742"]