module = "github.com/proglottis/gpgme"

description = """
Due to improper setting of finalizers, memory passed to C may be freed before it is used,
leading to crashes due to memory corruption or possible code execution.
"""

cve = "CVE-2020-8945"

credit = "Ulrich Obergfell"

[[versions]]
fixed = "v0.1.1"

[links]
commit = "https://github.com/proglottis/gpgme/commit/92153bcb59bd2f511e502262c46c7bd660e21733"
pr = "https://github.com/proglottis/gpgme/pull/23"