package = "github.com/justinas/nosurf"

description = """
[`VerifyToken`] can be bypassed if the expected token contains malformed Base64.
"""

credit = "@aeneasr"

symbols = ["VerifyToken", "verifyToken"]

[[versions]]
fixed = "v1.1.1"

[links]
commit = "https://github.com/justinas/nosurf/commit/4d86df7a4affa1fa50ab39fb09aac56c3ce9c314"
pr = "https://github.com/justinas/nosurf/pull/60"