module = "github.com/proglottis/gpgme"

description = """
The C bindings for the GPGME contain a number of use-after-free issues
which may lead to memory corruption and possible code execution.
"""

cve = "CVE-2020-8945"

published = "2021-04-14T12:00:00Z"

[[versions]]
fixed = "v0.1.1"

[links]
commit = "https://github.com/proglottis/gpgme/commit/92153bcb59bd2f511e502262c46c7bd660e21733"
context = ["https://bugzilla.redhat.com/show_bug.cgi?id=1795838"]