module = "github.com/ory/fosite"

description = """
Uniqueness of JWT IDs (jti) are not checked, allowing the JWT to be
replayed.
"""

cve = "CVE-2020-15222"

symbols = ["Fosite.AuthenticateClient"]

published = "2021-04-14T12:00:00Z"

[[versions]]
fixed = "v0.31.0"

[links]
commit = "https://github.com/ory/fosite/commit/0c9e0f6d654913ad57c507dd9a36631e1858a3e9"
context = ["https://github.com/ory/fosite/security/advisories/GHSA-v3q9-2p3m-7g43"]