module = "github.com/russellhaering/goxmldsig"

description = """
An XML message can be maliciously crafted such that signature
verification is bypassed.
"""

cve = "CVE-2020-15216"

credit = "Juho Nurminen (Mattermost)"

symbols = ["ValidationContext.findSignature"]

[[versions]]
fixed = "v1.1.0"

[links]
commit = "https://github.com/dexidp/dex/commit/324b1c886b407594196113a3dbddebe38eecd4e8"
context = ["https://github.com/russellhaering/goxmldsig/security/advisories/GHSA-q547-gmf8-8jr7"]