module = "github.com/gin-gonic/gin"

description = """
When used without an internet facing proxy, an adversary can spoof
their IP address by setting the X-Forwarded-For header.
"""

cve = "CVE-2020-28483"

credit = "@sorenh"

symbols = ["Context.ClientIP"]

[links]
pr = "https://github.com/gin-gonic/gin/pull/2632"
context = ["https://github.com/gin-gonic/gin/pull/2474"]