module = "aahframe.work"

description = """
[`HTTPEngine.Handle`] allows for directory traversal attacks due
to usage of unsanitized user input.
"""

credit = "@snyff"

symbols = ["HTTPEngine.Handle"]

[[versions]]
fixed = "v0.12.4"

[links]
commit = "https://github.com/go-aah/aah/commit/881dc9f71d1f7a4e8a9a39df9c5c081d3a2da1ec"
pr = "https://github.com/go-aah/aah/pull/267"
context = ["https://github.com/go-aah/aah/issues/266"]