package = "github.com/robbert229/jwt"

description = """
[`Validate`] used non-constant time string comparison to
compare a provided HMAC against expected HMAC, providing
a timing side-channel.
"""

symbols = ["Algorithm.validateSignature"]

[[versions]]
fixed = "v0.0.0-20170426191122-ca1404ee6e83"

[links]
commit = "https://github.com/robbert229/jwt/commit/ca1404ee6e83fcbafb66b09ed0d543850a15b654"
context = ["https://github.com/robbert229/jwt/issues/12"]