module = "github.com/tidwall/gjson"

description = """
Maliciously crafted JSON messages can cause an out-of-bounds panic.
"""

cve = "CVE-2020-36067"

credit = "@toptotu"

symbols = ["unwrap"]

[[versions]]
fixed = "v1.6.6"

[links]
commit = "https://github.com/tidwall/gjson/commit/bf4efcb3c18d1825b2988603dea5909140a5302b"
context = ["https://github.com/tidwall/gjson/issues/196"]